[project]
name = "taxifare"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Thanh An Vo", email = "thanhan25@gmail.com" }
]
requires-python = ">=3.12.9"
dependencies = [
    "bigquery>=0.0.45",
    "db-dtypes>=1.7.2",
    "google-cloud-bigquery[pandas]>=3.46.1",
    "matplotlib>=3.11.2",
    "pandas<3",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
taxifare = "taxifare:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
]
